namespace JPSCURA
{
    partial class AddOrderForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            panelWOaddorder = new Panel();
            txtGeneratedBy = new TextBox();
            lblGeneratedBy = new Label();
            btnAddOrder_WO = new Button();
            cmbStatus = new ComboBox();
            lblStatus = new Label();
            dtEndDate = new DateTimePicker();
            lblEndDate = new Label();
            lblStartDate = new Label();
            dtStartDate = new DateTimePicker();
            txtOrderTitle = new TextBox();
            lblOrderTitle = new Label();
            panelWOaddorder.SuspendLayout();
            SuspendLayout();
            // 
            // panelWOaddorder
            // 
            panelWOaddorder.BackColor = Color.RoyalBlue;
            panelWOaddorder.Controls.Add(txtGeneratedBy);
            panelWOaddorder.Controls.Add(lblGeneratedBy);
            panelWOaddorder.Controls.Add(btnAddOrder_WO);
            panelWOaddorder.Controls.Add(cmbStatus);
            panelWOaddorder.Controls.Add(lblStatus);
            panelWOaddorder.Controls.Add(dtEndDate);
            panelWOaddorder.Controls.Add(lblEndDate);
            panelWOaddorder.Controls.Add(lblStartDate);
            panelWOaddorder.Controls.Add(dtStartDate);
            panelWOaddorder.Controls.Add(txtOrderTitle);
            panelWOaddorder.Controls.Add(lblOrderTitle);
            panelWOaddorder.Dock = DockStyle.Fill;
            panelWOaddorder.Location = new Point(0, 0);
            panelWOaddorder.Margin = new Padding(3, 2, 3, 2);
            panelWOaddorder.Name = "panelWOaddorder";
            panelWOaddorder.RightToLeft = RightToLeft.No;
            panelWOaddorder.Size = new Size(1167, 338);
            panelWOaddorder.TabIndex = 0;
            panelWOaddorder.Paint += panelWOaddorder_Paint;
            // 
            // txtGeneratedBy
            // 
            txtGeneratedBy.Location = new Point(431, 109);
            txtGeneratedBy.Margin = new Padding(3, 2, 3, 2);
            txtGeneratedBy.Multiline = true;
            txtGeneratedBy.Name = "txtGeneratedBy";
            txtGeneratedBy.Size = new Size(112, 21);
            txtGeneratedBy.TabIndex = 10;
            // 
            // lblGeneratedBy
            // 
            lblGeneratedBy.Font = new Font("Arial", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblGeneratedBy.ForeColor = Color.White;
            lblGeneratedBy.Location = new Point(292, 107);
            lblGeneratedBy.Name = "lblGeneratedBy";
            lblGeneratedBy.Size = new Size(118, 23);
            lblGeneratedBy.TabIndex = 9;
            lblGeneratedBy.Text = "Generated By :";
            lblGeneratedBy.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // btnAddOrder_WO
            // 
            btnAddOrder_WO.BackColor = Color.LightSlateGray;
            btnAddOrder_WO.Cursor = Cursors.Hand;
            btnAddOrder_WO.FlatAppearance.BorderSize = 0;
            btnAddOrder_WO.FlatAppearance.MouseDownBackColor = Color.Gray;
            btnAddOrder_WO.FlatAppearance.MouseOverBackColor = Color.LightSteelBlue;
            btnAddOrder_WO.FlatStyle = FlatStyle.Flat;
            btnAddOrder_WO.Font = new Font("Arial", 10.2F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnAddOrder_WO.ForeColor = Color.SeaShell;
            btnAddOrder_WO.Location = new Point(431, 148);
            btnAddOrder_WO.Margin = new Padding(3, 2, 3, 2);
            btnAddOrder_WO.Name = "btnAddOrder_WO";
            btnAddOrder_WO.Size = new Size(113, 29);
            btnAddOrder_WO.TabIndex = 8;
            btnAddOrder_WO.Text = "Add Order";
            btnAddOrder_WO.UseVisualStyleBackColor = false;
            // 
            // cmbStatus
            // 
            cmbStatus.FormattingEnabled = true;
            cmbStatus.ItemHeight = 15;
            cmbStatus.Items.AddRange(new object[] { "Pending Order", "Future Order ", "Order In Process", "Finished Order" });
            cmbStatus.Location = new Point(133, 109);
            cmbStatus.Margin = new Padding(3, 2, 3, 2);
            cmbStatus.Name = "cmbStatus";
            cmbStatus.Size = new Size(154, 23);
            cmbStatus.TabIndex = 7;
            // 
            // lblStatus
            // 
            lblStatus.Font = new Font("Arial", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblStatus.ForeColor = Color.White;
            lblStatus.Location = new Point(15, 106);
            lblStatus.Name = "lblStatus";
            lblStatus.Size = new Size(113, 23);
            lblStatus.TabIndex = 6;
            lblStatus.Text = "Status      :";
            lblStatus.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // dtEndDate
            // 
            dtEndDate.CustomFormat = "";
            dtEndDate.Format = DateTimePickerFormat.Short;
            dtEndDate.Location = new Point(431, 67);
            dtEndDate.Margin = new Padding(3, 2, 3, 2);
            dtEndDate.Name = "dtEndDate";
            dtEndDate.Size = new Size(111, 23);
            dtEndDate.TabIndex = 5;
            // 
            // lblEndDate
            // 
            lblEndDate.Font = new Font("Arial", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblEndDate.ForeColor = Color.White;
            lblEndDate.Location = new Point(319, 68);
            lblEndDate.Name = "lblEndDate";
            lblEndDate.Size = new Size(91, 23);
            lblEndDate.TabIndex = 4;
            lblEndDate.Text = "End Date :";
            lblEndDate.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // lblStartDate
            // 
            lblStartDate.Font = new Font("Arial", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblStartDate.ForeColor = Color.White;
            lblStartDate.Location = new Point(15, 67);
            lblStartDate.Name = "lblStartDate";
            lblStartDate.Size = new Size(113, 23);
            lblStartDate.TabIndex = 3;
            lblStartDate.Text = "Start Date :";
            lblStartDate.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // dtStartDate
            // 
            dtStartDate.CustomFormat = "";
            dtStartDate.Format = DateTimePickerFormat.Short;
            dtStartDate.Location = new Point(133, 67);
            dtStartDate.Margin = new Padding(3, 2, 3, 2);
            dtStartDate.Name = "dtStartDate";
            dtStartDate.Size = new Size(154, 23);
            dtStartDate.TabIndex = 2;
            dtStartDate.Value = new DateTime(2026, 1, 2, 17, 23, 0, 0);
            // 
            // txtOrderTitle
            // 
            txtOrderTitle.Location = new Point(133, 25);
            txtOrderTitle.Margin = new Padding(3, 2, 3, 2);
            txtOrderTitle.Multiline = true;
            txtOrderTitle.Name = "txtOrderTitle";
            txtOrderTitle.Size = new Size(410, 24);
            txtOrderTitle.TabIndex = 1;
            // 
            // lblOrderTitle
            // 
            lblOrderTitle.Font = new Font("Arial", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblOrderTitle.ForeColor = Color.White;
            lblOrderTitle.Location = new Point(15, 25);
            lblOrderTitle.Name = "lblOrderTitle";
            lblOrderTitle.Size = new Size(113, 23);
            lblOrderTitle.TabIndex = 0;
            lblOrderTitle.Text = "Order Title :";
            lblOrderTitle.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // AddOrderForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1167, 338);
            Controls.Add(panelWOaddorder);
            FormBorderStyle = FormBorderStyle.None;
            Margin = new Padding(3, 2, 3, 2);
            Name = "AddOrderForm";
            Text = "AddOrderForm";
            Load += AddOrderForm_Load;
            panelWOaddorder.ResumeLayout(false);
            panelWOaddorder.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Panel panelWOaddorder;
        private TextBox txtOrderTitle;
        private Label lblOrderTitle;
        private DateTimePicker dtStartDate;
        private Label lblStartDate;
        private Label lblEndDate;
        private DateTimePicker dtEndDate;
        private Label lblStatus;
        private ComboBox cmbStatus;
        private Button btnAddOrder_WO;
        private TextBox txtGeneratedBy;
        private Label lblGeneratedBy;
    }
}